name = "sgdo-vidio25k" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sgdo.qyubisanz.us.kg"
custom_domain = true
[[routes]]
pattern = "updates.netflix.com.sgdo.qyubisanz.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sgdo.qyubisanz.us.kg"
custom_domain = true
[[routes]]
pattern = "support.udemy.com.sgdo.qyubisanz.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sgdo.qyubisanz.us.kg"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "ed542589-b669-4dfd-b84a-652b3f4c4087"
